routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('month');
});

// Route::get('/', 'ApplyController@index');
Route::get('/monthform', 'ApplyController@index');

Route::get('/daily', function () {
    return view('daily');
});
// Route::get('/daily', 'ApplyDailysController@index');
Route::get('/dailyform', 'ApplyDailysController@index');

Route::get('tothaiyear', function () {
    echo tothaiyear('2020-09-08');
});

Route::get('/regcomplete', function () {
    return view('regcomplete');
});

Route::get('/regdailycomplete', function () {
    return view('regdailycomplete');
});

Route::get('masterdatas/delete/{id}', 'MasterDatasController@destroy')->name('masterdatas_delete');
Route::resource('masterdatas', 'MasterDatasController');

Route::get('dailydatas/changeStatus/{id}/{status}', 'DailyDatasController@changeStatus')->name('dailydatas.changestatus');
Route::resource('dailydatas', 'DailyDatasController');

Route::get('/applyjob', 'ApplyController@index');
Route::post('/applyjobAction', 'ApplyController@applyjobAction');

Route::get('/applyjobdaily', 'ApplyDailysController@index');
Route::post('/applyjobdailyAction', 'ApplyDailysController@applyAction');
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::resource('/user', 'UserController');

Route::get('/addUser', function () {
    return view('auth/register');
});

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password','username','is_admin'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;

use App\User;

class UserController extends Controller
{
    public function __construct()
    {
        $this->middleware('isAdmin');
    }
    public function index(Request $request)
    {
        $keyword = $request->get('search');
        // $perPage = 25;
        $user = User::latest();

        if (!empty($keyword)) {
            $user = $user->where('name', 'like', '%'.$keyword.'%');
        }
        $user = $user->get();
        

        return view('user.index', compact('user'));
    }

    public function store(Request $request)
    {
        
        $requestData = $request->all();

        $request->validate([
            'name' => ['required', 'string', 'max:255'],
            'email' => ['required', 'string', 'email', 'max:255'],
            'username' => ['required', 'string',  'max:255', 'unique:users'],
            'password' => ['required', 'string', 'min:5', 'confirmed'],
        ]);

        // echo "password : ".$requestData['password'].", password_confirmation : ".$requestData['password_confirmation'];
        // exit();

        if(!($requestData['password']==$requestData['password_confirmation'])){
            return back()->withErrors(['password'=>'กรุณาระบุรหัสผ่านทีตรงกันค่ะ']);
        } 

        $requestData['password'] = bcrypt($requestData['password']);

        User::create($requestData);

        return redirect('user')->with('flash_message', ' added!');
    }

    public function show($id)
    {
        // $user = User::findOrFail($id);
        // // dd($user);
        // return view('editUser', compact('user'));
    }

    public function edit($id)
    {
        $user = User::findOrFail($id);
        // dd($user);

        return view('user.edit', compact('user'));
        return redirect()->route('user.edit');
    }

    public function update(Request $request, $id)
    {
        
        $requestData = $request->all();
        $user = User::findOrFail($id);

        // $user = auth()->user();  
        // dd($user);
        $userPassword = $user->password;
        
        $request->validate([
            'name' => ['required', 'string', 'max:255'],
            'email' => ['required', 'string', 'email', 'max:255'],
            // 'username' => ['required', 'string',  'max:255', 'unique:users'],
            'old_password' => 'required',
            'password' => 'required|same:password_confirmation|min:4',
            'password_confirmation' => 'required',
        ]);

        if(!Hash::check($requestData['old_password'], $userPassword)){
            return back()->withErrors(['old_password'=>'กรุณาระบุรหัสผ่านที่ถูกต้องค่ะ']);
        }        

        // $user->password = Hash::make($request->password);
        $requestData['password'] = bcrypt($requestData['password']);
        // $user->change_pass = '1';
        $user->update($requestData);
        // return redirect()->route('afterLogin');
        // return redirect('user')->with('success','User updated successfully');
        
        // $masterdata = User::findOrFail($id);
        // $masterdata->update($requestData);

        return redirect('user')->with('flash_message', ' updated!');
    }

    public function destroy($id)
    {
        User::destroy($id);

        return redirect('user')->with('flash_message', ' deleted!');
    }
}

resources/views/user/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Register') }}</div>

                <div class="card-body">
                    <form method="POST" action="{{ route('user.update', $user->id) }}">
                        @csrf
                        @method('PUT')
                        <div class="form-group row">
                            <label for="name" class="col-md-4 col-form-label text-md-right">{{ __('Name') }}</label>

                            <div class="col-md-6">
                                <input id="name" type="text" class="form-control @error('name') is-invalid @enderror" name="name" value="{{ $user->name }}" required autocomplete="name" autofocus>

                                @error('name')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="username" class="col-md-4 col-form-label text-md-right">{{ __('Username') }}</label>

                            <div class="col-md-6">
                                <input id="username" type="text" class="form-control @error('username') is-invalid @enderror" name="username" value="{{ $user->username }}" required autocomplete="username" autofocus>

                                @error('username')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="email" class="col-md-4 col-form-label text-md-right">{{ __('E-Mail Address') }}</label>

                            <div class="col-md-6">
                                <input id="email" type="email" class="form-control @error('email') is-invalid @enderror" name="email" value="{{ $user->email }}" required autocomplete="email">

                                @error('email')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="old_password" class="col-md-4 col-form-label text-md-right">{{ __('Old Password') }}</label>

                            <div class="col-md-6">
                                <input id="old_password" type="password" class="form-control @error('old_password') is-invalid @enderror" name="old_password" required autocomplete="new-password">

                                @error('old_password')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="password" class="col-md-4 col-form-label text-md-right">{{ __('Password') }}</label>

                            <div class="col-md-6">
                                <input id="password" type="password" class="form-control @error('password') is-invalid @enderror" name="password" required autocomplete="new-password">

                                @error('password')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="password-confirm" class="col-md-4 col-form-label text-md-right">{{ __('Confirm Password') }}</label>

                            <div class="col-md-6">
                                <input id="password-confirm" type="password" class="form-control" name="password_confirmation" required autocomplete="new-password">
                            </div>
                        </div>

                        <div class="form-group row mb-0">
                            <div class="col-md-2 offset-md-4 p-2">
                                <button type="submit" class="btn btn-primary">
                                    {{ __('Save') }}
                                </button>
                            </div>
                            <div class="col-md-2 offset-md-1 p-2">
                                <a href="{{ route('user.index') }}" class="btn btn-primary">
                                    {{ __('ย้อนกลับ') }}
                                </a>
                            </div>
                        </div>                        
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/user/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">User</div>
                    <div class="card-body">
                        <a href="{{ url('/addUser') }}" class="btn btn-success btn-sm" title="Add New MasterData">
                            <i class="fa fa-plus" aria-hidden="true"></i> Add New
                        </a>

                        <form method="GET" action="{{ url('/user') }}" accept-charset="UTF-8" class="form-inline my-2 my-lg-0 float-right" role="search">
                            <div class="input-group">
                                <input type="text" class="form-control" name="search" placeholder="Search..." value="{{ request('search') }}">
                                <span class="input-group-append">
                                    <button class="btn btn-secondary" type="submit">
                                        <i class="fa fa-search"></i>
                                    </button>
                                </span>
                            </div>
                        </form>

                        <br/>
                        <br/>
                        <div class="table-responsive">
                            <table class="table">
                                <thead>
                                    <tr>
                                        <th>#</th>
                                        <th>ชื่อ</th>
                                        <th>email</th>
                                        <th>username</th>
                                        <th>Actions</th>
                                    </tr>
                                </thead>
                                <tbody>
                                @foreach($user as $item)
                                    <tr>
                                        <td>{{ $loop->iteration }}</td>
                                        <td>{{ $item->name }} {{ $item->fname_th }} {{ $item->lname_th }}</td>
                                        <td>{{ $item->email }}</td>
                                        <td>{{ $item->username }}</td>
                                        <td>
                                            <a href="{{ url('user' . '/'. $item->id.'/edit') }}" title="View UserData"><button class="btn btn-info btn-sm"><i class="fa fa-eye" aria-hidden="true"></i> แก้ไข </button></a>
                                            {{-- @if (!empty($item->uploaddata->resume))
                                                <a href="{{ url($item->uploaddata->resume) }}" title="View MasterData" target='_blank'><button class="btn btn-info btn-sm"><i class="fa fa-file-pdf-o" aria-hidden="true"></i> Resumne</button></a>                                            
                                                
                                            @endif
                                            @if (!empty($item->uploaddata->private_info))
                                                <a href="{{ url($item->uploaddata->private_info) }}" title="View MasterData" target='_blank'><button class="btn btn-info btn-sm"><i class="fa fa-file-pdf-o" aria-hidden="true"></i> Info</button></a>                                            
                                                
                                            @endif --}}
                                            <form method="POST" action="{{ url('/user' . '/' . $item->id) }}" accept-charset="UTF-8" style="display:inline">
                                                {{ method_field('DELETE') }}
                                                {{ csrf_field() }}
                                                <button type="submit" class="btn btn-danger btn-sm" title="Delete MasterData" onclick="return confirm(&quot;Confirm delete?&quot;)"><i class="fa fa-trash-o" aria-hidden="true"></i></button>
                                            </form>
                                        </td>
                                    </tr>
                                @endforeach
                                </tbody>
                            </table>
                            {{-- <div class="pagination-wrapper"> {!! $masterdatas->appends(['search' => Request::get('search')])->render() !!} </div> --}}
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection