routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('month');
});

// Route::get('/', 'ApplyController@index');
Route::get('/monthform', 'ApplyController@index');

Route::get('/daily', function () {
    return view('daily');
});
// Route::get('/daily', 'ApplyDailysController@index');
Route::get('/dailyform', 'ApplyDailysController@index');

Route::get('tothaiyear', function () {
    echo tothaiyear('2020-09-08');
});

Route::get('/regcomplete', function () {
    return view('regcomplete');
});

Route::get('/regdailycomplete', function () {
    return view('regdailycomplete');
});

Route::get('masterdatas/delete/{id}', 'MasterDatasController@destroy')->name('masterdatas_delete');
Route::resource('masterdatas', 'MasterDatasController');

Route::get('dailydatas/changeStatus/{id}/{status}', 'DailyDatasController@changeStatus')->name('dailydatas.changestatus');
Route::resource('dailydatas', 'DailyDatasController');

Route::get('/applyjob', 'ApplyController@index');
Route::post('/applyjobAction', 'ApplyController@applyjobAction');

Route::get('/applyjobdaily', 'ApplyDailysController@index');
Route::post('/applyjobdailyAction', 'ApplyDailysController@applyAction');
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::resource('/user', 'UserController');

Route::get('/addUser', function () {
    return view('auth/register');
});

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">
    <link href='https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css'>
    <script src='https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js'></script>
<link href='https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.0.3/css/font-awesome.css'>
<script src='https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js'></script>
    <!-- Styles -->
    <link rel="stylesheet" href="{{ asset('font-awesome-4.7.0/css/font-awesome.min.css') }}">
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            {{--<li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                             @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif --}}
                        @else
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('user.index') }}">{{ __('User') }}</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('masterdatas.index') }}">ข้อมูลผู้สมัครงานรายเดือน</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('dailydatas.index') }}">ข้อมูลผู้สมัครงานรายวัน</a>
                            </li>
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }}
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                                        @csrf
                                    </form>
                                </div>                                
                            </li>

                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/layouts/apply.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>
                              
<link href="{{ asset('css/applyjobs.css') }}" rel="stylesheet">
                                <script type='text/javascript' src='https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js'></script>
                                <script type='text/javascript' src='https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js'></script>
                                <script type='text/javascript' src='https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js'></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-steps/1.1.0/jquery.steps.min.js"></script>
                                <script src="{{ asset('js/applyjobs.js') }}" defer></script>
</head>
<body class='snippet-body'>
    @yield('content')
                            </body>
                        </html>

resources/views/layouts/map.blade.php
<!DOCTYPE html>
<html>
<body>
<div id="googleMap" style="width:100%;height:800px;"></div>
@yield('content')
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDUxsUwOjdI8DXS0vDOneRaWo_s53WPg8k&callback=myMap"></script>
</body>
</html>

resources/views/layouts/step.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title> 
   <link href='https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css' rel='stylesheet'>
                                <link href='https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.0.3/css/font-awesome.css' rel='stylesheet'>
 
   
     <link rel="stylesheet" href="{{ asset('css/main.css') }}">
        <link rel="stylesheet" href="{{ asset('css/jquery.steps.css') }}">


 <script src="{{ asset('js/jquery-1.9.1.min.js') }}" ></script>
 
                                <script type='text/javascript' src='https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js'></script>
 <script src="{{ asset('js/modernizr-2.6.2.min.js') }}" ></script>

 <script src="{{ asset('js/jquery.cookie-1.3.1.js') }}" ></script>
                                <script src="{{ asset('js/jquery.steps.js') }}" ></script>
                                <script src="{{ asset('js/jquery.validate.js') }}"></script>
                                <script src="{{ asset('js/stepapplyjobs.js') }}" defer></script>
</head>
<body>
    <div id="app">
            <div style="max-width: 95%;margin-left:auto;margin-right:auto;">
    @yield('content')
    </div>
    </div>
                            </body>
                            
                        </html>

resources/views/layouts/stepdaily.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>สมัครงานลานนาเกษตร | LACO</title>
    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>
    <link href='https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css' rel='stylesheet'>
    <link href='https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.0.3/css/font-awesome.css' rel='stylesheet'>


    <link rel="stylesheet" href="{{ asset('css/main.css') }}">
    <link rel="stylesheet" href="{{ asset('css/jquery.step2.css') }}">


    <script src="{{ asset('js/jquery-1.9.1.min.js') }}"></script>

    <script type='text/javascript' src='https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js'></script>
    <script src="{{ asset('js/modernizr-2.6.2.min.js') }}"></script>

    <script src="{{ asset('js/jquery.cookie-1.3.1.js') }}"></script>
    <script src="{{ asset('js/jquery.steps.js') }}"></script>
    <script src="{{ asset('js/jquery.validate.js') }}"></script>
    <script src="{{ asset('js/dailystepapplyjobs.js?ver=20220425004') }}" defer></script>

    <style>
        .wrapper {
    overflow: auto;
    max-height: 400px;
    width: 100%;

    border: 2px solid black;
}
.term {
    overflow-y: auto;
}
    </style>
</head>

<body>
    <div id="app">
        <div style="max-width: 95%;margin-left:auto;margin-right:auto;">
            @yield('content')
        </div>
    </div>
</body>

</html>

resources/views/layouts/stepmonth.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>สมัครงานลานนาเกษตร | LACO</title>
    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>
    <link href='https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css' rel='stylesheet'>
    <link href='https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.0.3/css/font-awesome.css' rel='stylesheet'>


    <link rel="stylesheet" href="{{ asset('css/main.css') }}">
    <link rel="stylesheet" href="{{ asset('css/jquery.monthsteps.css') }}">


    <script src="{{ asset('js/jquery-1.9.1.min.js') }}"></script>

    <script type='text/javascript' src='https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js'></script>
    <script src="{{ asset('js/modernizr-2.6.2.min.js') }}"></script>

    <script src="{{ asset('js/jquery.cookie-1.3.1.js') }}"></script>
    <script src="{{ asset('js/jquery.steps.js') }}"></script>
    <script src="{{ asset('js/jquery.validate.js') }}"></script>
    <script src="{{ asset('js/monthstepapplyjobs.js?ver=20220425004') }}" defer></script>

    <style>
        .wrapper {
    overflow: auto;
    max-height: 400px;
    width: 100%;

    border: 2px solid black;
}
.term {
    overflow-y: auto;
}
    </style>
</head>

<body>
    <div id="app">
        <div style="max-width: 95%;margin-left:auto;margin-right:auto;">
            @yield('content')
        </div>
    </div>
</body>

</html>